const boardMembers = [
  {
    firstName: "Ben",
    lastName: "Issa",
    role: "President",
    description: "Can recognize most languages by listening to it",
    img: "./public/imgs/ben-issa.jpg",
    socials: {
      github: "https://github.com/ben-asmara",
      linkedin: "https://www.linkedin.com/in/ben-daouda/",
      email: null,
    },
  },
  {
    firstName: "Andrew",
    lastName: "Gutierrez",
    role: "Vice President",
    description: "Competes in video game tournaments sometimes",
    img: "./public/imgs/andrew-gutierrez.jpg",
    socials: {
      github: null,
      linkedin: "https://www.linkedin.com/in/andrew-gutierrez-8534a8385/",
      email: null,
    },
  },
  {
    firstName: "Joshua",
    lastName: "Padilla",
    role: "Treasurer",
    description: "Can play the guitar and tennis",
    img: "./public/imgs/joshua-padillia.jpg",
    socials: {
      github: null,
      linkedin: "https://www.linkedin.com/in/joshua-padilla-0a845813b/",
      email: null,
    },
  },
  {
    firstName: "Brian",
    lastName: "Fuentes",
    role: "Secretary",
    description: "A keyboard enthusiast",
    img: "./public/imgs/brian-fuentes.jpg",
    socials: {
      github: "https://github.com/brianf4",
      linkedin: "https://www.linkedin.com/in/brian-fuentes-18ab62182/",
      email: null,
    },
  },
  {
    firstName: "Alejandro",
    lastName: "Lopez",
    role: "Outreach Chair",
    description: "Loves Pokemon",
    img: "./public/imgs/alex-lopez.png",
    socials: {
      github: "https://github.com/alexghyet",
      linkedin: "https://www.linkedin.com/in/alejandro-lopez-45191b1a2/",
      email: null,
    },
  },
  {
    firstName: "Francis",
    lastName: "Agnyemang",
    role: "Events Chair",
    description: "Loves playing soccer, volleyball, and video games",
    img: "./public/imgs/francis-agnyemang.jpg",
    socials: {
      github: "https://github.com/rockynana",
      linkedin: "https://www.linkedin.com/in/francis-agyemang/",
      email: null,
    },
  },
  {
    firstName: "Grecia",
    lastName: "Campos",
    role: "Development Chair",
    description: "Loves going to concerts and puzzling",
    img: "./public/imgs/grecia-campos.jpg",
    socials: {
      github: null,
      linkedin: "https://www.linkedin.com/in/greciavcampos/",
      email: null,
    },
  },
  {
    firstName: "Thelma",
    lastName: "Ere",
    role: "Communications Chair",
    description: "Has an identical twin sister and loves going to concerts",
    img: "./public/imgs/thelma-ere.jpg",
    socials: {
      github: "https://github.com/ThelmaEre",
      linkedin: "https://www.linkedin.com/in/thelmaere/",
      email: null,
    },
  },
  {
    firstName: "Lynette",
    lastName: "Pena",
    role: "Communications Chair",
    description: "Loves to create social media content",
    img: "./public/imgs/lynette-pena.jpg",
    socials: {
      github: null,
      linkedin: "https://www.linkedin.com/in/lynette-pena-b70b67372/",
      email: null,
    },
  },
];
